-- 코드를 입력하세요
SELECT * 
FROM (
        SELECT CAR_ID, ROUND(AVG(END_DATE-START_DATE+1),1) AVERAGE_DURATION
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        GROUP BY CAR_ID
        ORDER BY 2 DESC, 1 DESC
     ) A
WHERE A.AVERAGE_DURATION >= 7

