SELECT NAME, DATETIME
FROM ANIMAL_INS AI INNER JOIN 
    (
    -- 입양을 못 간 동물 중, 보호소에 오래 있었던 동물 순위매기기
    SELECT AI.ANIMAL_ID, ROW_NUMBER() OVER (ORDER BY AI.DATETIME) ROWNUMBER
    FROM ANIMAL_INS AI LEFT OUTER JOIN ANIMAL_OUTS AO ON (AI.ANIMAL_ID = AO.ANIMAL_ID)
    WHERE AO.ANIMAL_ID IS NULL
    ) RN ON (AI.ANIMAL_ID = RN.ANIMAL_ID)
WHERE RN.ROWNUMBER <= 3
ORDER BY 2