SELECT FP.PRODUCT_ID, FP.PRODUCT_NAME, FP.PRICE * FO.TOTAL TOTAL_SALES
FROM FOOD_PRODUCT FP INNER JOIN 
    (
        SELECT PRODUCT_ID, SUM(AMOUNT) TOTAL
        FROM FOOD_ORDER
        WHERE TO_CHAR(PRODUCE_DATE,'YYYY-MM') = '2022-05'
        GROUP BY PRODUCT_ID
    ) FO ON (FP.PRODUCT_ID = FO.PRODUCT_ID)
ORDER BY 3 DESC, 1 ASC