SELECT HOUR, COUNT(A.DATETIME)
FROM ANIMAL_OUTS A RIGHT OUTER JOIN 
    (
    SELECT LEVEL - 1 HOUR
    FROM DUAL
    CONNECT BY LEVEL <= 24
    ) B ON (TO_CHAR(A.DATETIME,'HH24') = HOUR) 
GROUP BY HOUR
ORDER BY 1